spring:
  application:
    name: java-cafe

  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5532}/cafeteria
    username: ${POSTGRES_DB_USER:postgres}
    password: ${POSTGRES_DB_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-circular-references: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1